### ISSUE TITLE
Incorrect example from README

### ISSUE THREAD

**Issue by michaelmior** [ifak/fences#1]
The JSON Schema example from the README does not give the output that the README describes. There are significantly more valid examples than what is listed. The examples given are in fact valid, but the examples shown in the README are incomplete.

```
Valid:
{
    "foo": "",
    "bar": true
}
Valid:
{}
Valid:
{
    "foo": "",
    "bar": false
}
Valid:
""
Valid:
[
    "string"
]
Valid:
[
    42
]
Valid:
[
    null
]
Valid:
[
    true
]
Valid:
[
    false
]
Valid:
[
    {}
]
Valid:
[
    []
]
Valid:
true
Valid:
false
Valid:
0
Valid:
null
Invalid:
{
    "foo": 42
}
Invalid:
{
    "foo": null
}
Invalid:
{
    "foo": true,
    "bar": true
}
Invalid:
{
    "foo": false
}
Invalid:
{
    "foo": {},
    "bar": true
}
Invalid:
{
    "foo": []
}
Invalid:
{
    "bar": "string"
}
Invalid:
{
    "bar": 42
}
Invalid:
{
    "bar": null
}
Invalid:
{
    "bar": {}
}
Invalid:
{
    "bar": []
}
```

**Comment by otto-ifak** [comment]
@michaelmior Thank you for reporting this. I am very sorry for the late response - for some reason I did not received a notification from github :(
Anyway, I have fixed this in https://github.com/ifak/fences/commit/d523a0a69f55313967bc6acf072417c18ec868cb
